### ISSUE TITLE
New deployment failed

### ISSUE THREAD

**Issue by yawnbox** [cloudflare/wildebeest#227] opened 2023-02-08 23:01 UTC
I setup a new Cloudflare account, followed the directions...

<img width="947" alt="Screenshot 2023-02-08 at 2 57 48 PM" src="https://user-images.githubusercontent.com/8809920/217670433-6834b208-7b24-4174-ae97-c02237d17177.png">

Github job (deploy_to_cf_workers) failed with a warning:

```
Annotations
1 warning
[deploy](https://github.com/yawnbox/wildebeest/actions/runs/4129126395/jobs/7134393563)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Overall I would say deploying Wildebeest is not any easier than deploying Mastodon on a VM.

**Comment by yawnbox** [comment] 2023-02-08 23:07
<img width="1695" alt="Screenshot 2023-02-08 at 3 07 05 PM" src="https://user-images.githubusercontent.com/8809920/217671876-49ddcb5c-e450-47c4-95d7-5bcd93b43aa8.png">

**Comment by munkinasack** [comment] 2023-02-08 23:22
I just discovered this issue on my first attempt.

Including Images, you also have to subscribe to Worker's Paid plan.
Cloudflare Images $5/month min. Cloudflare Workers Paid- $5/month min. 

Based on the Readme, I had buy in with $5/month. I don't have buy in to do $10/month just for Wildebeet. 

I stoked that Cloudflare is contributing to the ActivityPub community. Sorry Cloudflare team.

**Comment by yawnbox** [comment] 2023-02-09 02:44
Thank you for the information. Unfortunately after I upgraded to a paid workers account, I ended up with the exact same error.

I agree the Readme is deceptive in cost.

**Comment by PrimeSitesCo** [comment] 2023-02-09 05:17
Also had the same issue. Got a Workers paid tier going and activated Durable Objects. Now getting slightly different error under download terraform state heading. I'd be expecting to see the account id where the "***" is being displayed below, so the process might be dropping that variable along the way possibly?

[ERROR] Failed to fetch https://api.cloudflare.com/client/v4/accounts/***/storage/kv/namespaces/890796349881474ca919f40a73588fbd/values/terraform.tfstate - 404: Not Found);

**Comment by xtuc** [comment] 2023-02-09 09:58
@PrimeSitesCo  I added a fix, could you please sync your fork? It will trigger a deploy build.

**Comment by celso** [comment] 2023-02-09 11:03
We will work on the tutorial and clarify the required subscriptions and associated costs.

**Comment by PrimeSitesCo** [comment] 2023-02-09 11:59
Thanks @xtuc, sync'd from main, but it didn't trigger a deploy. Manually re-ran the job and got past that step, but failed again at the Configure step I'm afraid. Something I did wrong perhaps?
<img width="1090" alt="Screenshot 2023-02-09 at 7 55 05 pm" src="https://user-images.githubusercontent.com/115609097/217806495-1cae0048-37ac-49ce-b9c0-3390997f6c8b.png">

**Comment by aidankinzett** [comment] 2023-02-09 12:45
I keep getting the same error `Error message: open terraform.tfstate: permission denied`. I've tried deleting the repo and starting again but I get the same error

**Comment by DataDrivenMD** [comment] 2023-02-09 16:41
> Have you tried to delete your KV namespaces starting with `wildebeest` and rerun?

Hi there - I've tried this, and it doesn't fix the problem. What I've been able to figure out thus far is that the default "Cloudflare Workers" API Token template lacks the permissions necessary to fully deploy the Terraform template. Unless I'm overlooking something obvious, I don't believe any of the repo documentation mentions the CF API token permissions necessary for deployment. It may help to start there.

**Comment by DataDrivenMD** [comment] 2023-02-09 17:36
<img width="1024" alt="error" src="https://user-images.githubusercontent.com/116459476/217890050-d15acfbc-2be5-448e-bb28-04ebd0fb2bf1.png">

During the latest attempt I was able to get as far as this error message (see image):
`error creating ruleset Wildebeest: exceeded maximum number of zone rulesets for phase 'http_request_firewall_managed'`

Of note, I have no rulesets on this account (0 across all zones), and the target zone is on the Pro plan.

By this point in the TF run the following items have already been configured: Images variants, metadata 2 KV namespaces, D1 instance, DO, Pages project, DNS record, and Zero Trust application. 
cc @xtuc

**Comment by xtuc** [comment] 2023-02-09 17:42
We are working to rewrite the README to provide better documentation and troubleshooting.

@DataDrivenMD 
You shouldn't use the default "Cloudflare Workers" API token template. There's a deploy button in the README that has a link to create an API token with the right permissions. 
Here's the link with the right template: https://dash.cloudflare.com/profile/api-tokens?permissionGroupKeys=[{%22key%22:%22d1%22,%22type%22:%22edit%22},{%22key%22:%22page%22,%22type%22:%22edit%22},{%22key%22:%22images%22,%22type%22:%22edit%22},{%22key%22:%22access%22,%22type%22:%22edit%22},{%22key%22:%22workers_kv_storage%22,%22type%22:%22edit%22},{%22key%22:%22access_acct%22,%22type%22:%22read%22},{%22key%22:%22dns%22,%22type%22:%22edit%22},{%22key%22:%22workers_scripts%22,%22type%22:%22edit%22},{%22key%22:%22account_rulesets%22,%22type%22:%22edit%22}]&name=Wildebeest

**Comment by koehn** [comment] 2023-02-09 17:52
I re-synced and opted in to the pay-as-you-go plan and when I re-run the job I am still getting the same message:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/wildebeest-do) failed.
[28](https://github.com/koehn/wildebeest/actions/runs/4136772123/jobs/7151559387#step:19:29)

[29](https://github.com/koehn/wildebeest/actions/runs/4136772123/jobs/7151559387#step:19:30)
  In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/***/workers/overview?enable-durable-objects [code: 10084]
```
The latter link (`dash.cloudflare.com...`) is broken.

**Comment by DataDrivenMD** [comment] 2023-02-09 17:57
> @DataDrivenMD You shouldn't use the default "Cloudflare Workers" API token template. There's a deploy button in the README that has a link to create an API token with the right permissions.

The magic link didn't work for me initially, which is why I ended up using the Workers Template. I wiped everything, disabled my browser's 3rd-party cookie blocker, then attempted Deploy to Cloudflare Workers button again-- that solved the API key issue. 

> Once Terraform created some resources. I strongly recommend not deleting anything manually. Resolving the permission / `error creating ruleset Wildebeest` is enough to unblock the deployement.

Yeah, I'm not touching anything once it is created unless I'm removing *all* resources before starting over from scratch.

> I asked internally about your `error creating ruleset Wildebeest` error.

FWIW/FYI @xtuc: one of my earliest attempts didn't encounter this error at all, and successfully produced a managed ruleset. I deleted that ruleset between attempts. Could it be that the now-deleted rulesets are still being counted against my account? If so, then I suspect others will eventually hit this roadblock, too.

**Comment by DataDrivenMD** [comment] 2023-02-09 18:01
@koehn: I ran into this issue earlier
> [29](https://github.com/koehn/wildebeest/actions/runs/4136772123/jobs/7151559387#step:19:30)
>   In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/***/workers/overview?enable-durable-objects [code: 10084]

The fix is to replace the *** with your CF account number, drop that into your browser URL bar, and you'll be prompted to agree. IOW:
`https://dash.cloudflare.com/<YOUR_CLOUDFLARE_ACCOUNT_NUMBER_GOES_HERE>/workers/overview?enable-durable-objects`

**Comment by xmflsct** [comment] 2023-02-09 18:07
@DataDrivenMD regarding creating ruleset error, can you help confirm if your target Pro zone is on the old or new managed rules? You can see a reference screenshot [here](https://support.cloudflare.com/hc/en-us/articles/5995821690637-Migrating-to-the-new-WAF-Managed-Rules#:~:text=Cloudflare%20dashboard%20changes). The one on the left indicates old managed rules, while the one on the right indicates new managed rules.

**Comment by DataDrivenMD** [comment] 2023-02-09 18:09
@xmflsct I can confirm that I am on the new managed rule interface

**Comment by xmflsct** [comment] 2023-02-09 18:13
@DataDrivenMD sorry deleted my previous message. Digged a bit more, you should have deployed managed rules already in that target zone. If that is the case, for now a workaround is to remove Terraform's config of managing WAF like [this commit](https://github.com/cloudflare/wildebeest/commit/8ededc89d9865bc39180d8c1f146085868463e60).

**Comment by DataDrivenMD** [comment] 2023-02-09 18:17
> @DataDrivenMD sorry deleted my previous message. Digged a bit more, you should have deployed managed rules already in that target zone. If that is the case, for now a workaround is to remove Terraform's config of managing WAF like [this commit](https://github.com/cloudflare/wildebeest/commit/8ededc89d9865bc39180d8c1f146085868463e60).

@xmflsct I don't have any deployed rules (at all). I'm happy to deploy the managed rules, but I believe that TF directive yields an *exception* to the managed rulesets. So, unless I'm misunderstanding the TF directive, the workaround would remove the bypass and thereby block ingress traffic to the `/inbox` endpoints.

**Comment by koehn** [comment] 2023-02-09 18:27
OK, just made sure my repo was sync’ed, enabled DO, Enabled Access, and now this error in the “Download Terraform State” task: 
```
✘ [ERROR] Failed to fetch https://api.cloudflare.com/client/v4/accounts/***/storage/kv/namespaces/[redacted]/values/terraform.tfstate - 404: Not Found);
```

**Comment by DataDrivenMD** [comment] 2023-02-09 18:35
> OK, just made sure my repo was sync’ed, enabled DO, Enabled Access, and now this error in the “Download Terraform State” task:
> 
> ```
> ✘ [ERROR] Failed to fetch https://api.cloudflare.com/client/v4/accounts/***/storage/kv/namespaces/[redacted]/values/terraform.tfstate - 404: Not Found);
> ```

@koehn Encountered this one, too. It happens because there's no `continue-on-error: true` directive in the GH Actions `deploy.yml` for that run command. The workaround is to follow the [Starting Over](https://github.com/cloudflare/wildebeest#troubleshooting) instructions. You may be able to get away without deleting the fork, but you definitely need to go through the steps to delete any KV Namespaces, DO objects, DNS records, and Zero Trust/Access Applications that were added by the Terraform config. Once you do that, hit re-run on the failed GH Actions job and cross your fingers.

**Comment by windymelt** [comment] 2023-02-09 18:36
I encountered simillar situation. I tried deployment but GitHub Action failed due to payment approval. Then I approved payment and re-run action to fail.

Situation is getting better when I removed all of related KV. Currently I got error:

```
│ Error: error creating Access Application for account "***": access.api.error.application_already_exists (11010)
│ 
│   with cloudflare_access_application.wildebeest_access,
│   on main.tf line 165, in resource "cloudflare_access_application" "wildebeest_access":
│  165: resource "cloudflare_access_application" "wildebeest_access" {
│ 
╵
╷
│ Error: failed to create ruleset "http_request_firewall_managed" as a similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first remove the existing rules otherwise you can remove the existing phase yourself using the API (https://api.cloudflare.com/#zone-rulesets-delete-zone-ruleset).
│ 
│   with cloudflare_ruleset.wildebeest_inbox,
│   on main.tf line 174, in resource "cloudflare_ruleset" "wildebeest_inbox":
│  174: resource "cloudflare_ruleset" "wildebeest_inbox" {
│ 
╵
```

What should I do?

**Comment by xmflsct** [comment] 2023-02-09 18:36
> > @DataDrivenMD sorry deleted my previous message. Digged a bit more, you should have deployed managed rules already in that target zone. If that is the case, for now a workaround is to remove Terraform's config of managing WAF like [this commit](https://github.com/cloudflare/wildebeest/commit/8ededc89d9865bc39180d8c1f146085868463e60).
> 
> @xmflsct I don't have any deployed rules (at all). I'm happy to deploy the managed rules, but I believe that TF directive yields an _exception_ to the managed rulesets. So, unless I'm misunderstanding the TF directive, the workaround would remove the bypass and thereby block ingress traffic to the `/inbox` endpoints.

That is likely you have deployed rules in the past through the dashboard UI, hence an entrypoint ruleset had been automatically created by the UI behind the scene. Tested that you need to call the API https://developers.cloudflare.com/api/operations/zone-rulesets-delete-a-zone-ruleset to delete that entrypoint ruleset, then it can be managed by Terraform.

**Comment by DataDrivenMD** [comment] 2023-02-09 19:13
@yawnbox  
> So... I did this `Visit the Access dashboard at https://dash.cloudflare.com/ and click the 'Enable Access' button.` and there is no such button.

It's been re-branded as "Zero Trust" (see image):

<img width="224" alt="zero" src="https://user-images.githubusercontent.com/116459476/217914292-66b069a7-120c-4c60-b26f-b136e8f21af6.png">

**Comment by koehn** [comment] 2023-02-09 19:15
To delete ruleset (requires `jq` and `curl`, your Zone ID and an API key (the one you used for you app is fine)):

1. Get ruleset:
```
curl --request GET   --url https://api.cloudflare.com/client/v4/zones/[zone id]/rulesets   --header 'Content-Type: application/json'   --header "Authorization: Bearer [API key]" | jq .
```
Look for the `id` of your app description “Ruleset for Wildebeest”
2. Delete ruleset: 
```
root@k3s-sd-01:~# curl --request DELETE   --url https://api.cloudflare.com/client/v4/zones/[zone id]/rulesets/[ruleset id]   --header 'Content-Type: application/json'   --header "Authorization: Bearer [API key]"
```

**Comment by DataDrivenMD** [comment] 2023-02-09 19:18
> I encountered simillar situation. I tried deployment but GitHub Action failed due to payment approval. Then I approved payment and re-run action to fail.
> 
> Situation is getting better when I removed all of related KV. Currently I got error:
> 
> ```
> │ Error: error creating Access Application for account "***": access.api.error.application_already_exists (11010)
> │ 
> │   with cloudflare_access_application.wildebeest_access,
> │   on main.tf line 165, in resource "cloudflare_access_application" "wildebeest_access":
> │  165: resource "cloudflare_access_application" "wildebeest_access" {
> │ 
> ╵
> ╷
> │ Error: failed to create ruleset "http_request_firewall_managed" as a similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first remove the existing rules otherwise you can remove the existing phase yourself using the API (https://api.cloudflare.com/#zone-rulesets-delete-zone-ruleset).
> │ 
> │   with cloudflare_ruleset.wildebeest_inbox,
> │   on main.tf line 174, in resource "cloudflare_ruleset" "wildebeest_inbox":
> │  174: resource "cloudflare_ruleset" "wildebeest_inbox" {
> │ 
> ╵
> ```
> 
> What should I do?

The workaround for the first error: 
1. From your main dashboard, click on Zero Trust to open a new tab with the Zero Trust Dashboard
2. From there, (see image) select Applications, then click "Delete" on the `wildebeest-XXXX` entry

For the second error, see @koehn's response ^^ but also see my earlier response to him regarding deleting the KV Namespaces, DNS Records, Pages Projects, etc.

Once you do that, re-run the failed GH Actions job.

<img width="488" alt="zero" src="https://user-images.githubusercontent.com/116459476/217915241-71f76e19-b776-4a29-8d29-4f8d192eff7a.png">

**Comment by xtuc** [comment] 2023-02-09 19:21
ruleset are a bit in a weird state because the UI in the dashboard hasn't shipped yet so only way is to use the API.

**Comment by yawnbox** [comment] 2023-02-09 19:22
> @yawnbox
> 
> > So... I did this `Visit the Access dashboard at https://dash.cloudflare.com/ and click the 'Enable Access' button.` and there is no such button.
> 
> It's been re-branded as "Zero Trust" (see image):
> 
> <img alt="zero" width="224" src="https://user-images.githubusercontent.com/116459476/217914292-66b069a7-120c-4c60-b26f-b136e8f21af6.png">

Thanks (again).

I walked through the pointless setting up of a free Zero Trust thing in which is charged my credit card $0. Re-ran the deploy, new error.

<img width="1696" alt="Screenshot 2023-02-09 at 11 21 13 AM" src="https://user-images.githubusercontent.com/8809920/217916261-a5fa85f6-b021-4229-b5e6-21b1030b5369.png">

**Comment by DataDrivenMD** [comment] 2023-02-09 19:28
> That is likely you have deployed rules in the past through the dashboard UI, hence an entrypoint ruleset had been automatically created by the UI behind the scene. Tested that you need to call the API https://developers.cloudflare.com/api/operations/zone-rulesets-delete-a-zone-ruleset to delete that entrypoint ruleset, then it can be managed by Terraform.

@xmflsct that did the trick, but for the record, the error wasn't due to any ruleset that I deployed, it was actually the orphaned wildebeest ruleset from an earlier (failed) run. Until the UI updates are shipped (h/t @xtuc), I would strongly recommend adding a CF API call to your deployment that checks whether the managed ruleset bypass already exists.

In fact, you'll probably need to do that for several steps along the Terraform deployment script in order to fix the numerous errors that trigger deployment failures due to pre-existing resources (see the comments from myself and others above). In the absence of such changes, I don't see how we won't keep running into these deployment roadblocks every time there's a substantive change to the project's infrastructure.

**Comment by DataDrivenMD** [comment] 2023-02-09 19:30
> I walked through the pointless setting up of a free Zero Trust thing in which it charged my credit card $0. Re-ran the deploy, new error.

That means you forgot to delete the KV Namespaces from an earlier failed run. [See my earlier comment for the workaround](https://github.com/cloudflare/wildebeest/issues/227#issuecomment-1424645979).

**Comment by DataDrivenMD** [comment] 2023-02-09 19:33
This has been the most time-consuming, convoluted "zero config" deployment I've ever attempted...but if you stick with it, eventually it works:

<img width="933" alt="deploy" src="https://user-images.githubusercontent.com/116459476/217918258-5ad745f7-0b14-4027-93ed-e3c01481ca5a.png">

**Comment by xtuc** [comment] 2023-02-09 19:36
Thanks for trying @DataDrivenMD. It helps us improve the documentation and deployement process.

**Comment by DataDrivenMD** [comment] 2023-02-09 19:38
> Thanks for trying @DataDrivenMD. It helps us improve the documentation and deployement process.

Thanks for being so responsive- that's what kept me going tbh. This is a great project, and happy to help smooth out the wrinkles.

**Comment by windymelt** [comment] 2023-02-09 19:54
@DataDrivenMD Everything worked well. Thank you very much for great application! I'll create account.

**Comment by yawnbox** [comment] 2023-02-09 20:03
> > I walked through the pointless setting up of a free Zero Trust thing in which it charged my credit card $0. Re-ran the deploy, new error.
> 
> That means you forgot to delete the KV Namespaces from an earlier failed run. [See my earlier comment for the workaround](https://github.com/cloudflare/wildebeest/issues/227#issuecomment-1424645979).

Thank you. I am new to CF, I don't know what that means, so for anyone reading this, it's under Workers:

<img width="318" alt="Screenshot 2023-02-09 at 11 42 29 AM" src="https://user-images.githubusercontent.com/8809920/217920447-7e25e531-6b70-418b-9605-c966425bb22f.png">

I needed to delete things in Overview, KV, and D1.

Yet again ran into another error after a new re-deploy, looks like the same one other folks have been getting.

```
│ Error: failed to create ruleset "http_request_firewall_managed" as a similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first remove the existing rules otherwise you can remove the existing phase yourself using the API (https://api.cloudflare.com/#zone-rulesets-delete-zone-ruleset).
[320](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:321)
│ 
[321](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:322)
│   with cloudflare_ruleset.wildebeest_inbox,
[322](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:323)
│   on main.tf line 174, in resource "cloudflare_ruleset" "wildebeest_inbox":
[323](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:324)
│  174: resource "cloudflare_ruleset" "wildebeest_inbox" {
[324](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:325)
│ 
[325](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:326)
╵
[326](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:327)
Error: Terraform exited with code 1.
[327](https://github.com/yawnbox/wildebeest/actions/runs/4137852844/jobs/7153536228#step:21:328)
Error: Process completed with exit code 1.
```

<img width="318" alt="Screenshot 2023-02-09 at 11 51 54 AM" src="https://user-images.githubusercontent.com/8809920/217922395-d7847fe5-1a9b-4885-8342-fd09f48df100.png">

Re-ran the deploy, it failed again. Went back to the dashboard and deleted everything, again. This time there was a DNS record for the domain, deleted it too.

<img width="318" alt="Screenshot 2023-02-09 at 11 58 11 AM" src="https://user-images.githubusercontent.com/8809920/217923663-f765dc8a-9c2b-4ed1-9c28-26ed3319ebee.png">

and... it failed again.

```
│ Error: error creating cloudflare pages project "wildebeest-yawnbox": A project with this name already exists. Choose a different project name. (8000002)
[315](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:316)
│ 
[316](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:317)
│   with cloudflare_pages_project.wildebeest_pages_project,
[317](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:318)
│   on main.tf line 101, in resource "cloudflare_pages_project" "wildebeest_pages_project":
[318](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:319)
│  101: resource "cloudflare_pages_project" "wildebeest_pages_project" {
[319](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:320)
│ 
[320](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:321)
╵
[321](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:322)
╷
[322](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:323)
│ Error: failed to create ruleset "http_request_firewall_managed" as a similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first remove the existing rules otherwise you can remove the existing phase yourself using the API (https://api.cloudflare.com/#zone-rulesets-delete-zone-ruleset).
[323](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:324)
│ 
[324](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:325)
│   with cloudflare_ruleset.wildebeest_inbox,
[325](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:326)
│   on main.tf line 174, in resource "cloudflare_ruleset" "wildebeest_inbox":
[326](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:327)
│  174: resource "cloudflare_ruleset" "wildebeest_inbox" {
[327](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:328)
│ 
[328](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:329)
╵
[329](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:330)
Error: Terraform exited with code 1.
[330](https://github.com/yawnbox/wildebeest/actions/runs/4137953565/jobs/7153766940#step:21:331)
Error: Process completed with exit code 1.
```

**Comment by DataDrivenMD** [comment] 2023-02-09 21:46
^^ The workaround for that last error is here: https://github.com/cloudflare/wildebeest/issues/227#issuecomment-1424690519

**Comment by PrimeSitesCo** [comment] 2023-02-10 06:54
Thanks, @DataDrivenMD. Made it to a successful deployment in the end following the Starting Over guide. Opened the Mastodon app on a mobile and managed to get through to the login interface of my new Wildebeest instance, but when I hit the register button I get a "Worker exceeded resource limit" error. Any suggestions as to what to adjust?
![IMG_B56FC54C054A-1](https://user-images.githubusercontent.com/115609097/218022731-53dffe41-dea3-479f-9009-376dff5ac209.jpeg)
![IMG_CBA56C604BF8-1](https://user-images.githubusercontent.com/115609097/218022764-f041d228-c4d3-4a9d-ad96-6aa9372baa33.jpeg)

**Comment by xtuc** [comment] 2023-02-10 09:55
@PrimeSitesCo can you please double check that Worker is set to unboud in Pages? If not, it requires a deployement to apply.

**Comment by PrimeSitesCo** [comment] 2023-02-10 10:00
@xtuc accessing either of the wildebeest-consumer-xxxxx and wildebeest-do workers show the little Unbound icon top-right.
<img width="109" alt="Screenshot 2023-02-10 at 5 57 41 pm" src="https://user-images.githubusercontent.com/115609097/218062043-873fe2a1-bb03-4616-80fb-caea4d2937e4.png">
Is that all I need to be looking out for?

**Comment by xtuc** [comment] 2023-02-10 10:04
@PrimeSitesCo  yes. The `Worker exceeded resource limit` happens during the registration because it generates your user's key pair and encrypt it to store in D1. Which might consume too much CPU or memory, but only required the first time you login in.

What client are you using? Official Mastodon app on iOS?

**Comment by xmflsct** [comment] 2023-02-10 10:15
@PrimeSitesCo it is under **Pages** that you need to set functions to unbound, see https://github.com/cloudflare/wildebeest#error-1102

**Comment by PrimeSitesCo** [comment] 2023-02-10 12:55
Thanks @xmflsct, that did the trick.

**Comment by DataDrivenMD** [comment] 2023-02-10 17:45
> Thanks @xmflsct, that did the trick.

Just seeing this message now, great to see that you found a fix @PrimeSitesCo

**Comment by TheSameCat2** [comment] 2023-02-10 23:36
I've been on the merry-go-round of errors listed here. Now I'm getting:
```error creating Access Application for account "***": access.api.error.invalid_request: domain does not belong to zone (12130)```
in the configure stage, right after the kv's are successfully created. Any clues from someone smarter than me?

**Comment by yawnbox** [comment] 2023-02-12 20:01
> ^^ The workaround for that last error is here: [#227 (comment)](https://github.com/cloudflare/wildebeest/issues/227#issuecomment-1424690519)

this presumes a great deal. I do not use Cloudflare. I do not interact with it with CLI. This makes no sense.

**Comment by DataDrivenMD** [comment] 2023-02-13 06:51
> > ^^ The workaround for that last error is here: [#227 (comment)](https://github.com/cloudflare/wildebeest/issues/227#issuecomment-1424690519)
> 
> this presumes a great deal. I do not use Cloudflare. I do not interact with it with CLI. This makes no sense. Am I hearing that for me to be able to deploy Wildebeest, I need to setup some other environment just to delete CF's mistakes?

I share your frustration. I don't work for CF, I'm just trying to help; I wish I could do more.

**Comment by xtuc** [comment] 2023-02-13 09:36
@yawnbox ruleset have been removed from the deployement because of the issues https://github.com/cloudflare/wildebeest/commit/9c570a5b0f9b5b34ccee99a06e2228a50f9d23d2. However, you'll need to delete the ruleset manually from your account using the API, as we don't have a UI in the dashboard yet.

**Comment by yawnbox** [comment] 2023-02-14 22:08
> @yawnbox ruleset have been removed from the deployement because of the issues [9c570a5](https://github.com/cloudflare/wildebeest/commit/9c570a5b0f9b5b34ccee99a06e2228a50f9d23d2). However, you'll need to delete the ruleset manually from your account using the API, as we don't have a UI in the dashboard yet.

Thanks, I'm just deleting my paid services from CF. This isn't turn key and is arguably harder to manage versus deploying Mastodon in a VM.

**Comment by xtuc** [comment] 2023-02-14 22:14
@yawnbox thanks for trying, we are improving the deployment process and documentations. I'll go ahead and close the issue for now.

**Closed by xtuc** 2023-02-14 22:14 UTC

**Comment by steinbring** [comment] 2023-02-19 14:57
I tried deploying just this morning (Feb 19) and I am still getting "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2.".  I tried "Sync Fork" and I am not behind the upstream branch.

**Comment by xtuc** [comment] 2023-02-20 11:18
`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2` is just a warning, it doesn't cause the deployement to fail.

I see in your logs:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/wildebeest-do) failed.

  In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/***/workers/overview?enable-durable-objects [code: 10084]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Please agree with the pricing and retry.

**Comment by louisbarclay** [comment] 2023-03-16 22:13
I've spent tons of time trying to deploy, and failing over and over again. I first deployed without agreeing to use DO, because it wasn't at all clear from the instructions [here](https://github.com/cloudflare/wildebeest/blob/main/docs/getting-started.md) that I needed to do that in advance. But now, I've started paying $5/m to Cloudflare workers, which I think means DO should be enabled (the ?enable-durable-objects link doesn't do anything special for me - and I am correctly changing it to have my account ID). I also tried deleting the D1 database after deploy, didn't work. Couldn't figure out any other things I should delete to try and make this work.

```
Total Upload: 1.13 KiB / gzip: 0.49 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/wildebeest-do) failed.

  In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/***/workers/overview?enable-durable-objects [code: 10084]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose

```

**Comment by louisbarclay** [comment] 2023-03-16 22:22
OK, turns out that paying for Cloudflare Workers did not actually enable DO. I managed to get link to work and bring up modal asking to agree to DO (which didn't come up before, even using that link). Got past DO part of deployment. Now failing here:

│ Error: failed to create DNS record: Authentication error (10000)

Going to try delete DNS records then attempt deploy again.

**Comment by maxtappenden** [comment] 2023-03-23 08:27
> OK, turns out that paying for Cloudflare Workers did not actually enable DO. I managed to get link to work and bring up modal asking to agree to DO (which didn't come up before, even using that link). Got past DO part of deployment. Now failing here:
> 
> 
> 
> │ Error: failed to create DNS record: Authentication error (10000)
> 
> 
> 
> Going to try delete DNS records then attempt deploy again.

Like you, I'm now paying for Cloudflare Workers, but don't appear to have DO enabled. How did you fix this?

The link in the error message doesn't work for me - I just get a 404.

**Comment by louisbarclay** [comment] 2023-03-23 17:01
@maxtappenden are you putting your Cloudflare user ID in the URL in place of ***?

**Comment by maxtappenden** [comment] 2023-03-23 17:06
> @maxtappenden are you putting your Cloudflare user ID in the URL in place of ***?

No! 😳 Didn't notice it. I only looked at the domain and the query string 😁

Thank you!

**Comment by 0xcaff** [comment] 2023-05-05 05:22
Regarding getting past the durable object error you gotta go here and scroll to the bottom of the page and click enable durable object

https://dash.cloudflare.com/accountId/workers/services/view/myWorker/production
